version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api.dev
      args:
        env: "development"
    working_dir: /api
    depends_on:
      - db
    environment:
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_URL=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=data
    command: uvicorn api.main:app --reload --host 0.0.0.0 --port 12321
    stdin_open: true
    tty: true
    restart: always
    ports:
      - "12321:12321"
    volumes:
      - ./api:/api

  db:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=data
    restart: always
    volumes:
      - ./db/data:/var/lib/postgresql/data