version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api.dev
      args:
        env: "development"
    working_dir: /api
    depends_on:
      - db
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    stdin_open: true
    tty: true
    restart: always
    ports:
      - "12321:8000"
    volumes:
      - ./api:/api

  db:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    restart: always
    volumes:
      - ./db/data:/var/lib/postgresql/data